module.exports = {
   cookies: [
      {
         domain: '.youtube.com',
         expirationDate: 1733384382.833789,
         hostOnly: false,
         httpOnly: true,
         name: 'GPS',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: '1',
         index: 0,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767942597.294517,
         hostOnly: false,
         httpOnly: false,
         name: 'PREF',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'f6=40000000&tz=Asia.Bangkok',
         index: 1,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764918583.425685,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSIDTS',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'sidts-CjIBQT4rXzT_nCanCFxSA3bncT-SGK35SVGW3Ta4RMEGPdKicgV-neUXP6oqDiDd-9fn3RAA',
         index: 2,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764918583.425789,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSIDTS',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'sidts-CjIBQT4rXzT_nCanCFxSA3bncT-SGK35SVGW3Ta4RMEGPdKicgV-neUXP6oqDiDd-9fn3RAA',
         index: 3,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767942583.425814,
         hostOnly: false,
         httpOnly: false,
         name: '__Secure-3PAPISID',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'Jir4aKiPLLwHd87b/ASebXiVMGER8pj8c5',
         index: 4,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767942583.425835,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSID',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'g.a000qwhsctymvM3pJ-LmwPIMjL3H5bvZ-SJmojYoPQGk6JCvuI-mx78O3gialDiavNcAGezwOQACgYKAeMSARASFQHGX2MiLubXJOM0TqBaf87R8N4x8hoVAUF8yKp0w1uBi0K05W_bNTgD55sM0076',
         index: 5,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767942594.944268,
         hostOnly: false,
         httpOnly: true,
         name: 'LOGIN_INFO',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AFmmF2swRQIhANzMpSR4bHbGiiRP3yI1N1yUkBhXie1jXfKn9zACky17AiBD8_MvL2ZbwuUeXm7RGoZatgQQdx9TgRJ74nb1OAWGJg:QUQ3MjNmemhwQ1A1UGtIWkZQR0M4djFhSXYtUkRLWllkMTRvbGVqdldjdmV5dFFsNmxQX0p3YldSbm5TbkFrblRzcEQwMXlXVjRGNXFkeFNRdGh2dnN4TjZYRmdfQVExY05QVXg0U1dWaUhoc0l5Vm42bkNnbVFtX21GaTJZdE5OdHQwTWtVcFlrR2lOYUdXblczLUNhTG1lVjBqSHk5cjNR',
         index: 6,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733382601,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-tladcw',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhANzMpSR4bHbGiiRP3yI1N1yUkBhXie1jXfKn9zACky17AiBD8_MvL2ZbwuUeXm7RGoZatgQQdx9TgRJ74nb1OAWGJg%3AQUQ3MjNmemhwQ1A1UGtIWkZQR0M4djFhSXYtUkRLWllkMTRvbGVqdldjdmV5dFFsNmxQX0p3YldSbm5TbkFrblRzcEQwMXlXVjRGNXFkeFNRdGh2dnN4TjZYRmdfQVExY05QVXg0U1dWaUhoc0l5Vm42bkNnbVFtX21GaTJZdE5OdHQwTWtVcFlrR2lOYUdXblczLUNhTG1lVjBqSHk5cjNR',
         index: 7,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733382602,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-3opvp5',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhANzMpSR4bHbGiiRP3yI1N1yUkBhXie1jXfKn9zACky17AiBD8_MvL2ZbwuUeXm7RGoZatgQQdx9TgRJ74nb1OAWGJg%3AQUQ3MjNmemhwQ1A1UGtIWkZQR0M4djFhSXYtUkRLWllkMTRvbGVqdldjdmV5dFFsNmxQX0p3YldSbm5TbkFrblRzcEQwMXlXVjRGNXFkeFNRdGh2dnN4TjZYRmdfQVExY05QVXg0U1dWaUhoc0l5Vm42bkNnbVFtX21GaTJZdE5OdHQwTWtVcFlrR2lOYUdXblczLUNhTG1lVjBqSHk5cjNR',
         index: 8,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733382601,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-l3hjtt',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhANzMpSR4bHbGiiRP3yI1N1yUkBhXie1jXfKn9zACky17AiBD8_MvL2ZbwuUeXm7RGoZatgQQdx9TgRJ74nb1OAWGJg%3AQUQ3MjNmemhwQ1A1UGtIWkZQR0M4djFhSXYtUkRLWllkMTRvbGVqdldjdmV5dFFsNmxQX0p3YldSbm5TbkFrblRzcEQwMXlXVjRGNXFkeFNRdGh2dnN4TjZYRmdfQVExY05QVXg0U1dWaUhoc0l5Vm42bkNnbVFtX21GaTJZdE5OdHQwTWtVcFlrR2lOYUdXblczLUNhTG1lVjBqSHk5cjNR',
         index: 9,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733382602,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-xuwub9',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhANzMpSR4bHbGiiRP3yI1N1yUkBhXie1jXfKn9zACky17AiBD8_MvL2ZbwuUeXm7RGoZatgQQdx9TgRJ74nb1OAWGJg%3AQUQ3MjNmemhwQ1A1UGtIWkZQR0M4djFhSXYtUkRLWllkMTRvbGVqdldjdmV5dFFsNmxQX0p3YldSbm5TbkFrblRzcEQwMXlXVjRGNXFkeFNRdGh2dnN4TjZYRmdfQVExY05QVXg0U1dWaUhoc0l5Vm42bkNnbVFtX21GaTJZdE5OdHQwTWtVcFlrR2lOYUdXblczLUNhTG1lVjBqSHk5cjNR',
         index: 10,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764918600.13661,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSIDCC',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AKEyXzXnw8gbaQXSpWccjHOXX6t2WHMyfHFe23E3jB5aJsb6wWPwc4esP9fWJBeob0AlfMHC7g',
         index: 11,
         isSearch: false,
      },
   ],
}
