module.exports = {
   cookies: [
      {
         domain: '.youtube.com',
         expirationDate: 1767886184.776719,
         hostOnly: false,
         httpOnly: false,
         name: 'PREF',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'f6=40000000&tz=Asia.Bangkok&f7=100',
         index: 0,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845591,
         hostOnly: false,
         httpOnly: false,
         name: 'SID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'g.a000qwhsctymvM3pJ-LmwPIMjL3H5bvZ-SJmojYoPQGk6JCvuI-mYsMxW_ZXCE7xhesPnHdO8gACgYKAUESARASFQHGX2MiiKPkR5IFX-6ND2ClR2TV-RoVAUF8yKr5qdrfv5qBphSifaZXCtDs0076',
         index: 1,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845716,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'g.a000qwhsctymvM3pJ-LmwPIMjL3H5bvZ-SJmojYoPQGk6JCvuI-mzxqw50Zp1y9ZgBQobrBVeAACgYKAWsSARASFQHGX2MiIFadFgkaHSQ0YyMK_me1fRoVAUF8yKpL1Jp7byUHrpC2IPw6N-8O0076',
         index: 2,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845731,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSID',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'g.a000qwhsctymvM3pJ-LmwPIMjL3H5bvZ-SJmojYoPQGk6JCvuI-mx78O3gialDiavNcAGezwOQACgYKAeMSARASFQHGX2MiLubXJOM0TqBaf87R8N4x8hoVAUF8yKp0w1uBi0K05W_bNTgD55sM0076',
         index: 3,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845748,
         hostOnly: false,
         httpOnly: true,
         name: 'HSID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'AkNMJJzYEl7JJNIzW',
         index: 4,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845761,
         hostOnly: false,
         httpOnly: true,
         name: 'SSID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'A5spPk58TRw7vLn99',
         index: 5,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845774,
         hostOnly: false,
         httpOnly: false,
         name: 'APISID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'N_wGNTiWMMOgeD6r/AGee_B6t-tNJILML8',
         index: 6,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845806,
         hostOnly: false,
         httpOnly: false,
         name: 'SAPISID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'Jir4aKiPLLwHd87b/ASebXiVMGER8pj8c5',
         index: 7,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845821,
         hostOnly: false,
         httpOnly: false,
         name: '__Secure-1PAPISID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'Jir4aKiPLLwHd87b/ASebXiVMGER8pj8c5',
         index: 8,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845836,
         hostOnly: false,
         httpOnly: false,
         name: '__Secure-3PAPISID',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'Jir4aKiPLLwHd87b/ASebXiVMGER8pj8c5',
         index: 9,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764861761.92705,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSIDTS',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'sidts-CjIBQT4rX0zrNQppTlAaeGeIuDoGjv-ZiYitaybp_TIF2FLcepTzPrJct8JmFzeYCPJbVhAA',
         index: 10,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764861761.927127,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSIDTS',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'sidts-CjIBQT4rX0zrNQppTlAaeGeIuDoGjv-ZiYitaybp_TIF2FLcepTzPrJct8JmFzeYCPJbVhAA',
         index: 11,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767886183.013187,
         hostOnly: false,
         httpOnly: true,
         name: 'LOGIN_INFO',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AFmmF2swRQIhAOUAUSyC4AnHod4hNl_v9GGDu76qgnXnDpscwuDTlP26AiA0xG-W4FRJuwNUM_53Df24Lm1XxouQ0LTTVWgl4988zg:QUQ3MjNmeENQbHhQTHpSdzNxZnVRVDB3VzFWQWxBOGhiMjUxX0xpbEV6TUdzSXF6cjFVaGFwNWg4SS1YOXk4MFZuYU80QzQ0OWJUQTZmeUdlNm85SFJZc0FHUTZTOUttSDBKT0RWRVNJLV9xcUZLRGxtTldXWWtzOXp6bXlxZ0NVbGQtV3VZSHl4dUt2WTZoQ2pLb01fT2N5YTh0eldFYnF3',
         index: 12,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733326196,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-sbra4i',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhALakrpZmT0K5tE8D7LVcuWFZMh-XDFXuHO8ojPC7fQaCAiAE3IZck0gjVtt4RYZd-rPd7Ch8-b8uNxYJ3yH9HVBeRA%3AQUQ3MjNmd0kyVnlIMHl6RFRyTk54YXpEZnJvOUVXU3YxQjFQN29qOWtJcktNMTktblhnNE1LU19iVTdKdmMwWnBVUEw5bGYyOXhNQ1l0QUVndUppM1FqTlAyOWNrbnRxbEtteDVEUXZGSVJicXp2eW1zRVNoXzN6czBZbnl6UEhkLVJ6UG9rM2RWN0hlRUpDTW1tR2ZjVmtYczhYTGlpQ0ZR',
         index: 13,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733326197,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-uwicob',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhAOUAUSyC4AnHod4hNl_v9GGDu76qgnXnDpscwuDTlP26AiA0xG-W4FRJuwNUM_53Df24Lm1XxouQ0LTTVWgl4988zg%3AQUQ3MjNmeENQbHhQTHpSdzNxZnVRVDB3VzFWQWxBOGhiMjUxX0xpbEV6TUdzSXF6cjFVaGFwNWg4SS1YOXk4MFZuYU80QzQ0OWJUQTZmeUdlNm85SFJZc0FHUTZTOUttSDBKT0RWRVNJLV9xcUZLRGxtTldXWWtzOXp6bXlxZ0NVbGQtV3VZSHl4dUt2WTZoQ2pLb01fT2N5YTh0eldFYnF3',
         index: 14,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733326199,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-183jmdn',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhAOUAUSyC4AnHod4hNl_v9GGDu76qgnXnDpscwuDTlP26AiA0xG-W4FRJuwNUM_53Df24Lm1XxouQ0LTTVWgl4988zg%3AQUQ3MjNmeENQbHhQTHpSdzNxZnVRVDB3VzFWQWxBOGhiMjUxX0xpbEV6TUdzSXF6cjFVaGFwNWg4SS1YOXk4MFZuYU80QzQ0OWJUQTZmeUdlNm85SFJZc0FHUTZTOUttSDBKT0RWRVNJLV9xcUZLRGxtTldXWWtzOXp6bXlxZ0NVbGQtV3VZSHl4dUt2WTZoQ2pLb01fT2N5YTh0eldFYnF3',
         index: 15,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764862194.737894,
         hostOnly: false,
         httpOnly: false,
         name: 'SIDCC',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'AKEyXzVGhDnGOyhii6CxxN6Iuxbq1C7xnXc73HflbXApKkV6Jmu1AxMbrNdHql9AAKavGTuy8E8',
         index: 16,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764862194.737978,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSIDCC',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AKEyXzXD-iWUTIVvaW6uIuCn_WLMyh7fGHKFlERw-WbaRE0GNZCXN6Rs4zAjlCHAirLpxlQKmFo',
         index: 17,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764862194.738,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSIDCC',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AKEyXzUqmemNAvqabQaz4J10lAked4FamWW_r_ej82peMWdA2dx0J4K_ZNUBnTEHZM9jme4whwk',
         index: 18,
         isSearch: false,
      },
   ],
}
