module.exports = {
   cookies: [
      {
         domain: '.youtube.com',
         expirationDate: 1767928242.863571,
         hostOnly: false,
         httpOnly: false,
         name: 'PREF',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'f6=40000000&tz=Asia.Bangkok&f7=100',
         index: 0,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845591,
         hostOnly: false,
         httpOnly: false,
         name: 'SID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'g.a000qwhsctymvM3pJ-LmwPIMjL3H5bvZ-SJmojYoPQGk6JCvuI-mYsMxW_ZXCE7xhesPnHdO8gACgYKAUESARASFQHGX2MiiKPkR5IFX-6ND2ClR2TV-RoVAUF8yKr5qdrfv5qBphSifaZXCtDs0076',
         index: 1,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845716,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'g.a000qwhsctymvM3pJ-LmwPIMjL3H5bvZ-SJmojYoPQGk6JCvuI-mzxqw50Zp1y9ZgBQobrBVeAACgYKAWsSARASFQHGX2MiIFadFgkaHSQ0YyMK_me1fRoVAUF8yKpL1Jp7byUHrpC2IPw6N-8O0076',
         index: 2,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845731,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSID',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'g.a000qwhsctymvM3pJ-LmwPIMjL3H5bvZ-SJmojYoPQGk6JCvuI-mx78O3gialDiavNcAGezwOQACgYKAeMSARASFQHGX2MiLubXJOM0TqBaf87R8N4x8hoVAUF8yKp0w1uBi0K05W_bNTgD55sM0076',
         index: 3,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845748,
         hostOnly: false,
         httpOnly: true,
         name: 'HSID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'AkNMJJzYEl7JJNIzW',
         index: 4,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845761,
         hostOnly: false,
         httpOnly: true,
         name: 'SSID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'A5spPk58TRw7vLn99',
         index: 5,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845774,
         hostOnly: false,
         httpOnly: false,
         name: 'APISID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'N_wGNTiWMMOgeD6r/AGee_B6t-tNJILML8',
         index: 6,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845806,
         hostOnly: false,
         httpOnly: false,
         name: 'SAPISID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'Jir4aKiPLLwHd87b/ASebXiVMGER8pj8c5',
         index: 7,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845821,
         hostOnly: false,
         httpOnly: false,
         name: '__Secure-1PAPISID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'Jir4aKiPLLwHd87b/ASebXiVMGER8pj8c5',
         index: 8,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767694607.845836,
         hostOnly: false,
         httpOnly: false,
         name: '__Secure-3PAPISID',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'Jir4aKiPLLwHd87b/ASebXiVMGER8pj8c5',
         index: 9,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764904222.952004,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSIDTS',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'sidts-CjIBQT4rX60AA8Qd3dTqJrjSUUYMaPEzZ97uebnHbfnNrXCqsWJr4qTRuxe4rjBtRxREcxAA',
         index: 10,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764904222.952119,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSIDTS',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'sidts-CjIBQT4rX60AA8Qd3dTqJrjSUUYMaPEzZ97uebnHbfnNrXCqsWJr4qTRuxe4rjBtRxREcxAA',
         index: 11,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1767928236.249066,
         hostOnly: false,
         httpOnly: true,
         name: 'LOGIN_INFO',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AFmmF2swRQIgKwvBu9ZJcb26ig6bFTxH00ByXITuPXqM6wUnkjBAPmMCIQCOpk7WMLZJ3bHWPokA6efKsVIVaBOHGRPwidnX3G2aVQ:QUQ3MjNmeHhVTEs2X0tGSFNBLTlTVW9Jc2c5aXJVbUdxY1pCY0FIcUM3RVpMYS1CMU81S0VnT0pLWTV4aC1rUTFuM3ZodUs4akx3blNqQUNOMUkwdlFkNnAwWEtuQVY3V1V3RllGRUR4WUxWaXd5X1YwVlFDNXktdUVyM1FvREVVRUY4ZFAtdHkyTGQ4TlUzUm1RNjY3emJVVGZrZlhnVjd3',
         index: 12,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733368251,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-3opvp5',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIgKwvBu9ZJcb26ig6bFTxH00ByXITuPXqM6wUnkjBAPmMCIQCOpk7WMLZJ3bHWPokA6efKsVIVaBOHGRPwidnX3G2aVQ%3AQUQ3MjNmeHhVTEs2X0tGSFNBLTlTVW9Jc2c5aXJVbUdxY1pCY0FIcUM3RVpMYS1CMU81S0VnT0pLWTV4aC1rUTFuM3ZodUs4akx3blNqQUNOMUkwdlFkNnAwWEtuQVY3V1V3RllGRUR4WUxWaXd5X1YwVlFDNXktdUVyM1FvREVVRUY4ZFAtdHkyTGQ4TlUzUm1RNjY3emJVVGZrZlhnVjd3',
         index: 13,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733368248,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-xuwub9',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIgKwvBu9ZJcb26ig6bFTxH00ByXITuPXqM6wUnkjBAPmMCIQCOpk7WMLZJ3bHWPokA6efKsVIVaBOHGRPwidnX3G2aVQ%3AQUQ3MjNmeHhVTEs2X0tGSFNBLTlTVW9Jc2c5aXJVbUdxY1pCY0FIcUM3RVpMYS1CMU81S0VnT0pLWTV4aC1rUTFuM3ZodUs4akx3blNqQUNOMUkwdlFkNnAwWEtuQVY3V1V3RllGRUR4WUxWaXd5X1YwVlFDNXktdUVyM1FvREVVRUY4ZFAtdHkyTGQ4TlUzUm1RNjY3emJVVGZrZlhnVjd3',
         index: 14,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1733368247,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-tladcw',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIgKwvBu9ZJcb26ig6bFTxH00ByXITuPXqM6wUnkjBAPmMCIQCOpk7WMLZJ3bHWPokA6efKsVIVaBOHGRPwidnX3G2aVQ%3AQUQ3MjNmeHhVTEs2X0tGSFNBLTlTVW9Jc2c5aXJVbUdxY1pCY0FIcUM3RVpMYS1CMU81S0VnT0pLWTV4aC1rUTFuM3ZodUs4akx3blNqQUNOMUkwdlFkNnAwWEtuQVY3V1V3RllGRUR4WUxWaXd5X1YwVlFDNXktdUVyM1FvREVVRUY4ZFAtdHkyTGQ4TlUzUm1RNjY3emJVVGZrZlhnVjd3',
         index: 15,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764904246.751683,
         hostOnly: false,
         httpOnly: false,
         name: 'SIDCC',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'AKEyXzWvv5MgAZyoosWMftlBq49nJPymnxL0OTn1RTmUlyO0BSy0sdyNWEyTGNAnmdQrwX0cdww',
         index: 16,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764904246.751779,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSIDCC',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AKEyXzX6mVoH6yDaOAL6C7w9fPJEkcB1Q7YQ3ZuPXCBAxT37ATx0pE3a61UA4PJ_mXBiTAGEKYY',
         index: 17,
         isSearch: false,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1764904246.751801,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSIDCC',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AKEyXzVVsfnWdg3sySqfuXioh2kpjwg7S_hQbJSpiP4p307DQHOkFiTS_G4XlzIcoU1reF1r86U',
         index: 18,
         isSearch: false,
      },
   ],
}
